// com.intrinio.fintech.localc
// Naming convention: https://wiki.openoffice.org/wiki/Documentation/DevGuide/AppendixA/General_Design_Rules

module com {
    module intrinio {
        module fintech {
            module localc {
                interface XIntrinio
                {
                  // Access code ID (e.g. com_fin_data), data key (e.g. limit, percent, current)
                  any IntrinioUsage( [in] string a, [in] string b );
                  // Identifier (e.g. ticker symbol), item (e.g. tag or series id)
                  any IntrinioDataPoint( [in] string identifier, [in] string item );
                  // ticker As String, Item As String, sequence As Integer, start_date As String, end_date As String, frequency As String
                  any IntrinioHistoricalPrices( [in] string ticker, [in] string item, [in] long sequencenumber,
                    [in] any startdate, [in] any enddate, [in] any frequency );
                  // identifier As String, Item As String, sequence As Integer, start_date As String, end_date As String, frequency As String
                  any IntrinioHistoricalData( [in] string identifier, [in] string item, [in] long sequencenumber,
                    [in] any startdate, [in] any enddate, [in] any frequency, [in] any periodtype,
                    [in] any showdate );
                  // Returns news article data for the selected identifier
                  any IntrinioNews( [in] string identifier, [in] string item, [in] long sequencenumber);
                  // Returns a list of available standardized fundamentals
                  any IntrinioFundamentals( [in] string ticker, [in] string statement, [in] string periodtype,
                    [in] long sequencenumber, [in] string item);
                  // Returns the standardized tags and labels for a given ticker, statement, and date or fiscal year/fiscal quarter.
                  any IntrinioTags( [in] string identifier, [in] string statement, [in] long sequencenumber, [in] string item);
                };
            };
        };
    };
};
